export const weather_code = {
    '沙尘暴': 'shachenbao',
    '霾': 'mai',
    '特大暴雨': 'tedabaoyu',
    '雷阵雨伴有冰雹': 'leizhenyubanyoubingbao',
    '雾': 'wu',
    '小雨': 'xiaoyu',
    '小雪': 'xiaoxue',
    '扬沙': 'yangsha',
    '阴': 'yin',
    '中雨': 'zhongyu',
    '雨夹雪': 'yujiaxue',
    '中雪': 'zhongxue',
    '阵雪': 'zhenxue',
    '阵雨': 'zhenyu',
    '暴雨': 'baoyu',
    '大雨': 'dayu',
    '暴雪': 'baoxue',
    '冻雨': 'dongyu',
    '大暴雨': 'dabaoyu',
    '大雪': 'daxue',
    '浮尘': 'fuchen',
    '多云': 'duoyun',
    '雷阵雨': 'leizhenyu',
    '强沙尘暴': 'qiangshachenbao',
    '晴': 'qing',
}